site_key: hespress_ar
name: Hespress Arabic
language: ar
base_url: "https://www.hespress.com/"
headers:
  User-Agent: "NewsScraperBot/1.0 (+https://example.com/hespress_ar)"
  Accept-Language: "ar,en-US;q=0.8"
timeout: 15
max_retries: 3
delay_seconds: 1.6

categories:
  economie: "/economie/"
  politique: "/politique/"
  sport: "/sport/"
  societe: "/societe/"
  culture: "/culture/"
  marocains-du-monde: "/marocains-du-monde/"
  orbites: "/orbites/"
  faits-divers: "/faits-divers/"
  art-culture: "/art-culture/"
  tv: "/tv/"
  automobile: "/automobile/"
  technologie: "/technologie/"
  home: "/"

pagination:
  type: suffix
  first_page: ""
  next_page: "page/{page}/"

filters:
  exclude_substrings:
    - "/auteur/"
    - "/tag/"
    - "/wp-admin/"
    - "?print"
    - "utm"

selectors:
  article_links:
    - ".overlay.card a.stretched-link"
    - "article.card a.card-link"
    - "h2 a"
    - "h3 a"
    - ".article-box a"
    - ".titre a"
  title:
    - "h1.entry-title"
    - "h1.post-title"
  content:
    - "div.entry-content"
    - ".article-content"
    - "article"
    - ".content"
    - ".entry-content"

  content_remove:
    - ".sharedaddy"
    - ".post-share"
    - ".tags"
    - ".related"
    - "script"
    - "style"
  author:
    - ".author a"
    - ".byline a"
  date:
    - { css: "time[datetime]", attr: "datetime" }
    - { css: 'meta[property="article:published_time"]', attr: "content" }
  category:
    - ".breadcrumb .breadcrumb-item:last-child a"
    - ".post-categories a"
    - 'meta[property="article:section"]'
  image:
    - { css: 'meta[property="og:image"]', attr: "content" }
    - "img.wp-post-image"
# Add these lines:
take_screenshots: true  # Enable screenshots
screenshot_timeout: 10000  # 10 seconds timeout