site_key: snrtnews
name: "SNRT News"
base_url: "https://snrtnews.com"
language: "ar"

categories:
  الأنشطة_الأميرية: "/hashtag/%D8%A7%D9%84%D8%A3%D9%86%D8%B4%D8%B7%D8%A9%D8%A7%D9%84%D8%A3%D9%85%D9%8A%D8%B1%D9%8A%D8%A9"
  سياسة: "/thematique/%D8%B3%D9%8A%D8%A7%D8%B3%D8%A9"
  رياضة: "/thematique/%D8%B1%D9%8A%D8%A7%D8%B6%D8%A9"
  مجتمع: "/thematique/%D9%85%D8%AC%D8%AA%D9%85%D8%B9"
  اقتصاد: "/thematique/%D8%A5%D9%82%D8%AA%D8%B5%D8%A7%D8%AF"
  إفريقيا: "/thematique/%D8%A5%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7"
  العالم: "/thematique/%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85"
  فن_وثقافة: "/thematique/art-et-culture"
  تكنولوجيا: "/thematique/%D8%AA%D9%83%D9%86%D9%88%D9%84%D9%88%D8%AC%D9%8A%D8%A7"

selectors:
  article_links:
    - 'a[href*="/article/"]'

  title:
    - 'div.detail-secinfo div.titre-article h1'

  date:
    - 'span.info-date p'

  author:
    - 'span.info-auteur'

  content:
    - 'div.detail-secinfo div.description-article'

  image:
    - 'div.detail-secinfo div.img-article img'